// <auto-generated />
using Beca.PlaylistInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beca.PlaylistInfo.API.Migrations
{
    [DbContext(typeof(PlaylistInfoContext))]
    partial class PlaylistInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "La bachata que más nos gusta.",
                            Name = "Bachata Remix"
                        },
                        new
                        {
                            Id = 2,
                            Description = "El reggaeton que más nos gusta.",
                            Name = "Reggaeton Remix"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tus canciones de pop más escuchadas.",
                            Name = "Coldplay Remix"
                        });
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayListId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Canción buenísima de nuestro amigo Manuel Turizo que está llenando conciertos.",
                            Name = "La Bachata - Manuel Turizo",
                            PlayListId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Clasicazo de canción, nunca puede faltar cuando hablamos de bachata.",
                            Name = "Propuesta Indecente - Romeo Santos",
                            PlayListId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Si necesitas descripción para semejante temazo seguramente seas menor de edad.",
                            Name = "La Gasolina",
                            PlayListId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Canción de Feid de su álbum Cumpleaños Feliz.",
                            Name = "Normal - Ferxxo",
                            PlayListId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Himno de Coldplay, no necesita más descripición.",
                            Name = "The Scientist",
                            PlayListId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Otra de sus más famosas canciones, bárbaro.",
                            Name = "Adventure Of A Lifetime",
                            PlayListId = 3
                        });
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Song", b =>
                {
                    b.HasOne("Beca.PlaylistInfo.API.Entities.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });
#pragma warning restore 612, 618
        }
    }
}
